#!/usr/bin/env bash
# Installs Nginx with the following configurations:
# Listens on port 80.
# Returns a page containing "Hello World!" when queried
# at the root with a curl GET request.

# updates the package lists for available software packages.
echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# initializing nginx service
sudo service nginx start

# permitting nginx on firewall
sudo ufw allow 'Nginx HTTP'

# offer the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# making new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted. ✅\n"
