#!/usr/bin/env bash
# Sets up a Nginx server to accept connections on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
