#!/usr/bin/env bash
# write loop from 1 to 10 and print:
#   "bad luck" for the 4th iteration
#   "good luck" for 8th iteration
#   "Best School" for all

h=0

while [ $h -lt 10 ]
do
 if [$h -eq 3]
 then
   echo "bad luck"
 elif [ $h -eq 7 ]
 then
   echo "good luck"
 else
   echo "Best School"
 fi
 (( h++ ))
done
