#!/usr/bin/env bash
# Write numbers from 1 to 20, add:
#  "bad luck from China" for 4th iteration
#  "bad luck from Japan" for 9th iteration
#  "bad luck from Italy" for 17th iteration

num=1

while [ $num -le 20 ]
do
  echo "$num"
  case $num in
    "4" ) echo "bad luck from China";;
    "9" ) echo "bad luck from Japa";;
    "17" ) echo "bad luck from Italy";;
  esac
  (( num++ ))
done
