#!/usr/bin/env bash
# write the time for 12 hours and 59 minutes
#  show hours from 0 to 12
#  show minnutes from 1 to 59

hour=0

while [ $hour -le 12 ]
do
  echo "Hour : $hour"
  min=1
  while [ $min -le 59 ]
  do
  echo "$minute"
  (( min++ ))
  done
  (( hour ++ ))
done
